config:
  name: 在线_v6
#  parameters: #卡迪尔 参数
#    x: "${get_ksid}"


teststeps:
-
  name: 获configId,serverID
  request:
    method: GET
    headers:
      temp-id: ${get_temp_id}
    url: /text/chat-set/chat/config/getAssignConfig/4
    # data:
    #   channelType: 0

  extract:
    get_configId: $.item.configId
    get_updateServiceId: $.item.updateServiceId

  export:
    - get_configId
    - get_updateServiceId

  validate:
    - eq: [ $..retCode,'000000' ]
#    - eq: [ $..keyword, '${del_keyWord}']
#  deciId": "83d4039186d8452b88a59873bfcf2084 == 客服列表 对应的是serviceId=客服列表


