/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScheduledTasksRouteImport } from './routes/scheduled-tasks'
import { Route as RecordRouteImport } from './routes/record'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CastRouteImport } from './routes/cast'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ApiTestingRouteImport } from './routes/api-testing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledTasksRoute = ScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CastRoute = CastRouteImport.update({
  id: '/cast',
  path: '/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestingRoute = ApiTestingRouteImport.update({
  id: '/api-testing',
  path: '/api-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-testing': typeof ApiTestingRoute
  '/automation': typeof AutomationRoute
  '/browser': typeof BrowserRoute
  '/cast': typeof CastRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/record': typeof RecordRoute
  '/scheduled-tasks': typeof ScheduledTasksRoute
  '/security': typeof SecurityRoute
  '/templates': typeof TemplatesRoute
  '/terminal': typeof TerminalRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-testing': typeof ApiTestingRoute
  '/automation': typeof AutomationRoute
  '/browser': typeof BrowserRoute
  '/cast': typeof CastRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/record': typeof RecordRoute
  '/scheduled-tasks': typeof ScheduledTasksRoute
  '/security': typeof SecurityRoute
  '/templates': typeof TemplatesRoute
  '/terminal': typeof TerminalRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-testing': typeof ApiTestingRoute
  '/automation': typeof AutomationRoute
  '/browser': typeof BrowserRoute
  '/cast': typeof CastRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/record': typeof RecordRoute
  '/scheduled-tasks': typeof ScheduledTasksRoute
  '/security': typeof SecurityRoute
  '/templates': typeof TemplatesRoute
  '/terminal': typeof TerminalRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-testing'
    | '/automation'
    | '/browser'
    | '/cast'
    | '/chat'
    | '/history'
    | '/logs'
    | '/record'
    | '/scheduled-tasks'
    | '/security'
    | '/templates'
    | '/terminal'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-testing'
    | '/automation'
    | '/browser'
    | '/cast'
    | '/chat'
    | '/history'
    | '/logs'
    | '/record'
    | '/scheduled-tasks'
    | '/security'
    | '/templates'
    | '/terminal'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-testing'
    | '/automation'
    | '/browser'
    | '/cast'
    | '/chat'
    | '/history'
    | '/logs'
    | '/record'
    | '/scheduled-tasks'
    | '/security'
    | '/templates'
    | '/terminal'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiTestingRoute: typeof ApiTestingRoute
  AutomationRoute: typeof AutomationRoute
  BrowserRoute: typeof BrowserRoute
  CastRoute: typeof CastRoute
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRoute
  LogsRoute: typeof LogsRoute
  RecordRoute: typeof RecordRoute
  ScheduledTasksRoute: typeof ScheduledTasksRoute
  SecurityRoute: typeof SecurityRoute
  TemplatesRoute: typeof TemplatesRoute
  TerminalRoute: typeof TerminalRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled-tasks': {
      id: '/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/scheduled-tasks'
      preLoaderRoute: typeof ScheduledTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cast': {
      id: '/cast'
      path: '/cast'
      fullPath: '/cast'
      preLoaderRoute: typeof CastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-testing': {
      id: '/api-testing'
      path: '/api-testing'
      fullPath: '/api-testing'
      preLoaderRoute: typeof ApiTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiTestingRoute: ApiTestingRoute,
  AutomationRoute: AutomationRoute,
  BrowserRoute: BrowserRoute,
  CastRoute: CastRoute,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRoute,
  LogsRoute: LogsRoute,
  RecordRoute: RecordRoute,
  ScheduledTasksRoute: ScheduledTasksRoute,
  SecurityRoute: SecurityRoute,
  TemplatesRoute: TemplatesRoute,
  TerminalRoute: TerminalRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
